### ISSUE TITLE
404 Not Found: @sinonjs/commons@^1.0.2

### ISSUE THREAD

**Issue by cncook001** [sinonjs/commons#6]
Related to https://github.com/sinonjs/formatio/issues/14

with a line like this in .npmrc:
```
_auth="test"
```
I get this:
```
$ npm install @sinonjs/commons@1.0.2
npm ERR! code E404
npm ERR! 404 Not Found: @sinonjs/commons@1.0.2
```
This works though, even with the _auth line in .npmrc
```
$ npm install @sinonjs/formatio@3.0.0
+ @sinonjs/formatio@3.0.0
updated 1 package and audited 5 packages in 0.627s
found 0 vulnerabilities
```

$ npm --version
6.4.0

**Comment by mroderick** [comment]
I have not been able to reproduce this issue using `_auth="test"` in a project specific `.npmrc`.

The problem you encounter looks like the same class of problem as people were having with formatio, which so far have all been local problems caused by proxies, caches and local settings.

If you're using a registry that is not https://registry.npmjs.org/, where the Sinon modules are published, then the problem is most likely with the registry.

You can see which registry you're using by running this command.

```shell
npm config get registry
```

**Comment by cncook001** [comment]
Looks like I was using npm from /usr/local/lib/node_modules.  I wiped that and used nvm version instead.

To recreate...

```
$ npm install express-generator -g
/Users/craig/.nvm/versions/node/v8.9.4/bin/express -> /Users/craigcook/.nvm/versions/node/v8.9.4/lib/node_modules/express-generator/bin/express-cli.js
+ express-generator@4.16.0
added 10 packages in 1.638s
```
```
$ echo "_auth=\"test\"" > ./npmrc
```
```
$ npm config get registry
https://registry.npmjs.org/
```
```$ cat .npmrc
_auth="test"
```
```
$ npm install @sinonjs/commons@1.0.2
npm ERR! code E404
npm ERR! 404 Not Found: @sinonjs/commons@1.0.2

npm ERR! A complete log of this run can be found in:
npm ERR!      /Users/craig/.npm/_logs/2018-10-11T16_57_44_200Z-debug.log
```
```cat /Users/craigcook/.npm/_logs/2018-10-11T16_57_44_200Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/craig/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/Users/craig/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@sinonjs/commons@1.0.2' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 6abaef0cbfea6d99
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@sinonjs%2fcommons 663ms
8 silly fetchPackageMetaData error for @sinonjs/commons@1.0.2 404 Not Found: @sinonjs/commons@1.0.2
9 verbose stack Error: 404 Not Found: @sinonjs/commons@1.0.2
9 verbose stack     at fetch.then.res (/Users/craig/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/Users/craig/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/Users/craig/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/Users/craig/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/Users/craig/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/Users/craig/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/Users/craig/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/Users/craig/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/Users/craig/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:789:20)
9 verbose stack     at tryOnImmediate (timers.js:751:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
10 verbose cwd /Users/craig/git/myapp
11 verbose Darwin 17.7.0
12 verbose argv "/Users/craig/.nvm/versions/node/v8.9.4/bin/node" "/Users/craig/.nvm/versions/node/v8.9.4/bin/npm" "install" "@sinonjs/commons@1.0.2"
13 verbose node v8.9.4
14 verbose npm  v5.6.0
15 error code E404
16 error 404 Not Found: @sinonjs/commons@1.0.2
17 verbose exit [ 1, true ]
```

**Comment by cncook001** [comment]
After you install the express generator run this
```
 express myapp
cd myapp
```

**Comment by cncook001** [comment]
Workaround is to use Sinon version 6.1.0
